spring:
  application:
    name: ecommerce

  server:
    port: 8080
    address: 0.0.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  security:
    jwt:
      private-key: classpath:keys/jwt-private.key
      public-key: classpath:keys/jwt-public.key

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: '*'
